# pandas #

In [16]:
import pandas as pd

In [17]:
import sys
print(sys.executable)

c:\Users\sarah\OneDrive\Desktop\numpy\.venv\Scripts\python.exe

In [18]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [19]:
df=pd.DataFrame({"Name":["Sarah","bushra","Arsh"],
                 "Marks":[89,56,78]})
df

     Name  Marks
0   Sarah     89
1  bushra     56
2    Arsh     78

In [20]:
df = pd.read_csv("iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [21]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [22]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [23]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

## data Selection ##

In [26]:
df[["petal_length","sepal_length"]]

     petal_length  sepal_length
0             1.4           5.1
1             1.4           4.9
2             1.3           4.7
3             1.5           4.6
4             1.4           5.0
..            ...           ...
145           5.2           6.7
146           5.0           6.3
147           5.2           6.5
148           5.4           6.2
149           5.1           5.9

[150 rows x 2 columns]

In [27]:
df.iloc[0]

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

In [28]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [29]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [30]:
df2=pd.read_csv("iris.csv")

In [31]:
df2

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             NaN          3.0           1.4          0.2     setosa
2             4.7          3.2           NaN          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [33]:
df2.dropna()

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[148 rows x 5 columns]

In [34]:
df2.fillna(0)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             0.0          3.0           1.4          0.2     setosa
2             4.7          3.2           0.0          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [38]:
df2.rename(columns={"sepal_length":"SL"},inplace=True)

In [36]:
df2

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             NaN          3.0           1.4          0.2     setosa
2             4.7          3.2           NaN          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [41]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SL            149 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  149 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [43]:
df2['SL'] = df2['SL'].fillna(0).astype(int)

In [44]:
df2['SL']

0      5
1      0
2      4
3      4
4      5
      ..
145    6
146    6
147    6
148    6
149    5
Name: SL, Length: 150, dtype: int64

In [47]:
print(df2.to_string(index=False))

 SL  sepal_width  petal_length  petal_width    species
  5          3.5           1.4          0.2     setosa
  0          3.0           1.4          0.2     setosa
  4          3.2           NaN          0.2     setosa
  4          3.1           1.5          0.2     setosa
  5          3.6           1.4          0.2     setosa
  5          3.9           1.7          0.4     setosa
  4          3.4           1.4          0.3     setosa
  5          3.4           1.5          0.2     setosa
  4          2.9           1.4          0.2     setosa
  4          3.1           1.5          0.1     setosa
  5          3.7           1.5          0.2     setosa
  4          3.4           1.6          0.2     setosa
  4          3.0           1.4          0.1     setosa
  4          3.0           1.1          0.1     setosa
  5          4.0           1.2          0.2     setosa
  5          4.4           1.5          0.4     setosa
  5          3.9           1.3          0.4     setosa
  5          3.5           1.4          0.3     setosa
  5          3.8           1.7          0.3     setosa
  5          3.8           1.5          0.3     setosa
  5          3.4           1.7          0.2     setosa
  5          3.7           1.5          0.4     setosa
  4          3.6           1.0          0.2     setosa
  5          3.3           1.7          0.5     setosa
  4          3.4           1.9          0.2     setosa
  5          3.0           1.6          0.2     setosa
  5          3.4           1.6          0.4     setosa
  5          3.5           1.5          0.2     setosa
  5          3.4           1.4          0.2     setosa
  4          3.2           1.6          0.2     setosa
  4          3.1           1.6          0.2     setosa
  5          3.4           1.5          0.4     setosa
  5          4.1           1.5          0.1     setosa
  5          4.2           1.4          0.2     setosa
  4          3.1           1.5          0.2     setosa
  5          3.2           1.2          0.2     setosa
  5          3.5           1.3          0.2     setosa
  4          3.6           1.4          0.1     setosa
  4          3.0           1.3          0.2     setosa
  5          3.4           1.5          0.2     setosa
  5          3.5           1.3          0.3     setosa
  4          2.3           1.3          0.3     setosa
  4          3.2           1.3          0.2     setosa
  5          3.5           1.6          0.6     setosa
  5          3.8           1.9          0.4     setosa
  4          3.0           1.4          0.3     setosa
  5          3.8           1.6          0.2     setosa
  4          3.2           1.4          0.2     setosa
  5          3.7           1.5          0.2     setosa
  5          3.3           1.4          0.2     setosa
  7          3.2           4.7          1.4 versicolor
  6          3.2           4.5          1.5 versicolor
  6          3.1           4.9          1.5 versicolor
  5          2.3           4.0          1.3 versicolor
  6          2.8           4.6          1.5 versicolor
  5          2.8           4.5          1.3 versicolor
  6          3.3           4.7          1.6 versicolor
  4          2.4           3.3          1.0 versicolor
  6          2.9           4.6          1.3 versicolor
  5          2.7           3.9          1.4 versicolor
  5          2.0           3.5          1.0 versicolor
  5          3.0           4.2          1.5 versicolor
  6          2.2           4.0          1.0 versicolor
  6          2.9           4.7          1.4 versicolor
  5          2.9           3.6          1.3 versicolor
  6          3.1           4.4          1.4 versicolor
  5          3.0           4.5          1.5 versicolor
  5          2.7           4.1          1.0 versicolor
  6          2.2           4.5          1.5 versicolor
  5          2.5           3.9          1.1 versicolor
  5          3.2           4.8          1.8 versicolor
  6          2.8           4.0          1.3 versicolor
  6          2.5           4.9          1.5 versicolor
  6          2.8           4.7          1.2 versicolor
  6          2.9           4.3          1.3 versicolor
  6          3.0           4.4          1.4 versicolor
  6          2.8           4.8          1.4 versicolor
  6          3.0           5.0          1.7 versicolor
  6          2.9           4.5          1.5 versicolor
  5          2.6           3.5          1.0 versicolor
  5          2.4           3.8          1.1 versicolor
  5          2.4           3.7          1.0 versicolor
  5          2.7           3.9          1.2 versicolor
  6          2.7           5.1          1.6 versicolor
  5          3.0           4.5          1.5 versicolor
  6          3.4           4.5          1.6 versicolor
  6          3.1           4.7          1.5 versicolor
  6          2.3           4.4          1.3 versicolor
  5          3.0           4.1          1.3 versicolor
  5          2.5           4.0          1.3 versicolor
  5          2.6           4.4          1.2 versicolor
  6          3.0           4.6          1.4 versicolor
  5          2.6           4.0          1.2 versicolor
  5          2.3           3.3          1.0 versicolor
  5          2.7           4.2          1.3 versicolor
  5          3.0           4.2          1.2 versicolor
  5          2.9           4.2          1.3 versicolor
  6          2.9           4.3          1.3 versicolor
  5          2.5           3.0          1.1 versicolor
  5          2.8           4.1          1.3 versicolor
  6          3.3           6.0          2.5  virginica
  5          2.7           5.1          1.9  virginica
  7          3.0           5.9          2.1  virginica
  6          2.9           5.6          1.8  virginica
  6          3.0           5.8          2.2  virginica
  7          3.0           6.6          2.1  virginica
  4          2.5           4.5          1.7  virginica
  7          2.9           6.3          1.8  virginica
  6          2.5           5.8          1.8  virginica
  7          3.6           6.1          2.5  virginica
  6          3.2           5.1          2.0  virginica
  6          2.7           5.3          1.9  virginica
  6          3.0           5.5          2.1  virginica
  5          2.5           5.0          2.0  virginica
  5          2.8           5.1          2.4  virginica
  6          3.2           5.3          2.3  virginica
  6          3.0           5.5          1.8  virginica
  7          3.8           6.7          2.2  virginica
  7          2.6           6.9          2.3  virginica
  6          2.2           5.0          1.5  virginica
  6          3.2           5.7          2.3  virginica
  5          2.8           4.9          2.0  virginica
  7          2.8           6.7          2.0  virginica
  6          2.7           4.9          1.8  virginica
  6          3.3           5.7          2.1  virginica
  7          3.2           6.0          1.8  virginica
  6          2.8           4.8          1.8  virginica
  6          3.0           4.9          1.8  virginica
  6          2.8           5.6          2.1  virginica
  7          3.0           5.8          1.6  virginica
  7          2.8           6.1          1.9  virginica
  7          3.8           6.4          2.0  virginica
  6          2.8           5.6          2.2  virginica
  6          2.8           5.1          1.5  virginica
  6          2.6           5.6          1.4  virginica
  7          3.0           6.1          2.3  virginica
  6          3.4           5.6          2.4  virginica
  6          3.1           5.5          1.8  virginica
  6          3.0           4.8          1.8  virginica
  6          3.1           5.4          2.1  virginica
  6          3.1           5.6          2.4  virginica
  6          3.1           5.1          2.3  virginica
  5          2.7           5.1          1.9  virginica
  6          3.2           5.9          2.3  virginica
  6          3.3           5.7          2.5  virginica
  6          3.0           5.2          2.3  virginica
  6          2.5           5.0          1.9  virginica
  6          3.0           5.2          2.0  virginica
  6          3.4           5.4          2.3  virginica
  5          3.0           5.1          1.8  virginica

In [49]:
pd.concat([df,df2])

     sepal_length  sepal_width  petal_length  petal_width    species   SL
0             5.1          3.5           1.4          0.2     setosa  NaN
1             4.9          3.0           1.4          0.2     setosa  NaN
2             4.7          3.2           1.3          0.2     setosa  NaN
3             4.6          3.1           1.5          0.2     setosa  NaN
4             5.0          3.6           1.4          0.2     setosa  NaN
..            ...          ...           ...          ...        ...  ...
145           NaN          3.0           5.2          2.3  virginica  6.0
146           NaN          2.5           5.0          1.9  virginica  6.0
147           NaN          3.0           5.2          2.0  virginica  6.0
148           NaN          3.4           5.4          2.3  virginica  6.0
149           NaN          3.0           5.1          1.8  virginica  5.0

[300 rows x 6 columns]